<?php

namespace CR\GSBRBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * praticienRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class praticienRepository extends EntityRepository {

    public function findAll() {
        return $this->findBy(array(), array('nomMedecin' => 'ASC'));
    }

}
