<?php

namespace CR\GSBRBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * rapportVisiteRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class rapportVisiteRepository extends EntityRepository {

    public function getRapportByVisiteur($id) {
//        $query = $this->_em->createQuery('SELECT nomMedecin, prenomMedecin, MAX(dateRapport) FROM rapportVisite R INNER JOIN praticien P ON R.medecin_id = P.id WHERE visiteur_id = :id GROUP BY medecin_id');
        $qb = $this->createQueryBuilder('r')
                ->select('MAX(r.dateRapport) as date', 'm.nomMedecin', 'COUNT(m.nomMedecin) as nbRapport')
                ->join('r.medecin', 'm')
                ->where('r.visiteur = :id')
                ->groupBy('m.nomMedecin');

        $qb->setParameter('id', $id);

        return $qb->getQuery()->getResult();
    }

}
