<?php

namespace CR\GSBRBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * visiteurRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class visiteurRepository extends EntityRepository {

    public function findVisiteur($login, $mdp) {
        $query = $this->getEntityManager()
                ->createQuery('
            SELECT v.id, v.nom, v.prenom 
            FROM CRGSBRBundle:visiteur v
            WHERE v.login = :login
            AND v.mdp = :mdp'
                );
        $query->setParameters(array('login' => $login, 'mdp' => $mdp));

        $results = $query->execute();
        $results->fetch();

        return $results;

    }

}
