security:
    firewalls:
        dev:
            pattern:  ^/(_(profiler|wdt)|css|images|js)/
            security: false
        connexion_firewall:
            pattern:    ^/connexion$
            anonymous:  ~
        secured_area:
            pattern:    ^/
            form_login:
                login_path:  /connexion
                check_path:  /connexion_check
            logout:
                path:   /deconnexion
                target: /connexion

    access_control:
        - { path: ^/connexion, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/, roles: ROLE_ADMIN }
    providers:
        main:
            entity: { class: CR\GSBRBundle\Entity\visiteur, property: login }


    encoders:
        Symfony\Component\Security\Core\User\User: plaintext
        CR\GSBRBundle\Entity\visiteur: plaintext