<?php

namespace Proxies\__CG__\CR\GSBRBundle\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class visiteur extends \CR\GSBRBundle\Entity\visiteur implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array();



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return array('__isInitialized__', '' . "\0" . 'CR\\GSBRBundle\\Entity\\visiteur' . "\0" . 'id', '' . "\0" . 'CR\\GSBRBundle\\Entity\\visiteur' . "\0" . 'idGSB', '' . "\0" . 'CR\\GSBRBundle\\Entity\\visiteur' . "\0" . 'nom', '' . "\0" . 'CR\\GSBRBundle\\Entity\\visiteur' . "\0" . 'prenom', '' . "\0" . 'CR\\GSBRBundle\\Entity\\visiteur' . "\0" . 'login', '' . "\0" . 'CR\\GSBRBundle\\Entity\\visiteur' . "\0" . 'mdp', '' . "\0" . 'CR\\GSBRBundle\\Entity\\visiteur' . "\0" . 'adresse', '' . "\0" . 'CR\\GSBRBundle\\Entity\\visiteur' . "\0" . 'cp', '' . "\0" . 'CR\\GSBRBundle\\Entity\\visiteur' . "\0" . 'ville', '' . "\0" . 'CR\\GSBRBundle\\Entity\\visiteur' . "\0" . 'dateEmbauche');
        }

        return array('__isInitialized__', '' . "\0" . 'CR\\GSBRBundle\\Entity\\visiteur' . "\0" . 'id', '' . "\0" . 'CR\\GSBRBundle\\Entity\\visiteur' . "\0" . 'idGSB', '' . "\0" . 'CR\\GSBRBundle\\Entity\\visiteur' . "\0" . 'nom', '' . "\0" . 'CR\\GSBRBundle\\Entity\\visiteur' . "\0" . 'prenom', '' . "\0" . 'CR\\GSBRBundle\\Entity\\visiteur' . "\0" . 'login', '' . "\0" . 'CR\\GSBRBundle\\Entity\\visiteur' . "\0" . 'mdp', '' . "\0" . 'CR\\GSBRBundle\\Entity\\visiteur' . "\0" . 'adresse', '' . "\0" . 'CR\\GSBRBundle\\Entity\\visiteur' . "\0" . 'cp', '' . "\0" . 'CR\\GSBRBundle\\Entity\\visiteur' . "\0" . 'ville', '' . "\0" . 'CR\\GSBRBundle\\Entity\\visiteur' . "\0" . 'dateEmbauche');
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (visiteur $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', array());
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', array());
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', array());

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function setIdGSB($idGSB)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setIdGSB', array($idGSB));

        return parent::setIdGSB($idGSB);
    }

    /**
     * {@inheritDoc}
     */
    public function getIdGSB()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIdGSB', array());

        return parent::getIdGSB();
    }

    /**
     * {@inheritDoc}
     */
    public function setNom($nom)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNom', array($nom));

        return parent::setNom($nom);
    }

    /**
     * {@inheritDoc}
     */
    public function getNom()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNom', array());

        return parent::getNom();
    }

    /**
     * {@inheritDoc}
     */
    public function setPrenom($prenom)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPrenom', array($prenom));

        return parent::setPrenom($prenom);
    }

    /**
     * {@inheritDoc}
     */
    public function getPrenom()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPrenom', array());

        return parent::getPrenom();
    }

    /**
     * {@inheritDoc}
     */
    public function setUsername($login)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setUsername', array($login));

        return parent::setUsername($login);
    }

    /**
     * {@inheritDoc}
     */
    public function getUsername()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getUsername', array());

        return parent::getUsername();
    }

    /**
     * {@inheritDoc}
     */
    public function setPassword($mdp)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPassword', array($mdp));

        return parent::setPassword($mdp);
    }

    /**
     * {@inheritDoc}
     */
    public function getPassword()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPassword', array());

        return parent::getPassword();
    }

    /**
     * {@inheritDoc}
     */
    public function getMdp()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getMdp', array());

        return parent::getMdp();
    }

    /**
     * {@inheritDoc}
     */
    public function setAdresse($adresse)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setAdresse', array($adresse));

        return parent::setAdresse($adresse);
    }

    /**
     * {@inheritDoc}
     */
    public function getAdresse()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getAdresse', array());

        return parent::getAdresse();
    }

    /**
     * {@inheritDoc}
     */
    public function setCp($cp)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCp', array($cp));

        return parent::setCp($cp);
    }

    /**
     * {@inheritDoc}
     */
    public function getCp()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCp', array());

        return parent::getCp();
    }

    /**
     * {@inheritDoc}
     */
    public function setVille($ville)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setVille', array($ville));

        return parent::setVille($ville);
    }

    /**
     * {@inheritDoc}
     */
    public function getVille()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getVille', array());

        return parent::getVille();
    }

    /**
     * {@inheritDoc}
     */
    public function setDateEmbauche($dateEmbauche)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDateEmbauche', array($dateEmbauche));

        return parent::setDateEmbauche($dateEmbauche);
    }

    /**
     * {@inheritDoc}
     */
    public function getDateEmbauche()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDateEmbauche', array());

        return parent::getDateEmbauche();
    }

    /**
     * {@inheritDoc}
     */
    public function eraseCredentials()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'eraseCredentials', array());

        return parent::eraseCredentials();
    }

    /**
     * {@inheritDoc}
     */
    public function getRoles()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getRoles', array());

        return parent::getRoles();
    }

    /**
     * {@inheritDoc}
     */
    public function getSalt()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getSalt', array());

        return parent::getSalt();
    }

}
