<?php

namespace Proxies\__CG__\CR\GSBRBundle\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class praticien extends \CR\GSBRBundle\Entity\praticien implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array();



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return array('__isInitialized__', '' . "\0" . 'CR\\GSBRBundle\\Entity\\praticien' . "\0" . 'id', '' . "\0" . 'CR\\GSBRBundle\\Entity\\praticien' . "\0" . 'nomMedecin', '' . "\0" . 'CR\\GSBRBundle\\Entity\\praticien' . "\0" . 'prenomMedecin', '' . "\0" . 'CR\\GSBRBundle\\Entity\\praticien' . "\0" . 'adresseMedecin', '' . "\0" . 'CR\\GSBRBundle\\Entity\\praticien' . "\0" . 'cpMedecin', '' . "\0" . 'CR\\GSBRBundle\\Entity\\praticien' . "\0" . 'villeMedecin', '' . "\0" . 'CR\\GSBRBundle\\Entity\\praticien' . "\0" . 'coefNotoriete', '' . "\0" . 'CR\\GSBRBundle\\Entity\\praticien' . "\0" . 'typeMedecin');
        }

        return array('__isInitialized__', '' . "\0" . 'CR\\GSBRBundle\\Entity\\praticien' . "\0" . 'id', '' . "\0" . 'CR\\GSBRBundle\\Entity\\praticien' . "\0" . 'nomMedecin', '' . "\0" . 'CR\\GSBRBundle\\Entity\\praticien' . "\0" . 'prenomMedecin', '' . "\0" . 'CR\\GSBRBundle\\Entity\\praticien' . "\0" . 'adresseMedecin', '' . "\0" . 'CR\\GSBRBundle\\Entity\\praticien' . "\0" . 'cpMedecin', '' . "\0" . 'CR\\GSBRBundle\\Entity\\praticien' . "\0" . 'villeMedecin', '' . "\0" . 'CR\\GSBRBundle\\Entity\\praticien' . "\0" . 'coefNotoriete', '' . "\0" . 'CR\\GSBRBundle\\Entity\\praticien' . "\0" . 'typeMedecin');
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (praticien $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', array());
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', array());
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', array());

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function setNomMedecin($nomMedecin)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNomMedecin', array($nomMedecin));

        return parent::setNomMedecin($nomMedecin);
    }

    /**
     * {@inheritDoc}
     */
    public function getNomMedecin()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNomMedecin', array());

        return parent::getNomMedecin();
    }

    /**
     * {@inheritDoc}
     */
    public function setPrenomMedecin($prenomMedecin)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPrenomMedecin', array($prenomMedecin));

        return parent::setPrenomMedecin($prenomMedecin);
    }

    /**
     * {@inheritDoc}
     */
    public function getPrenomMedecin()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPrenomMedecin', array());

        return parent::getPrenomMedecin();
    }

    /**
     * {@inheritDoc}
     */
    public function setCpMedecin($cpMedecin)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCpMedecin', array($cpMedecin));

        return parent::setCpMedecin($cpMedecin);
    }

    /**
     * {@inheritDoc}
     */
    public function getCpMedecin()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCpMedecin', array());

        return parent::getCpMedecin();
    }

    /**
     * {@inheritDoc}
     */
    public function setVilleMedecin($villeMedecin)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setVilleMedecin', array($villeMedecin));

        return parent::setVilleMedecin($villeMedecin);
    }

    /**
     * {@inheritDoc}
     */
    public function getVilleMedecin()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getVilleMedecin', array());

        return parent::getVilleMedecin();
    }

    /**
     * {@inheritDoc}
     */
    public function setCoefNotoriete($coefNotoriete)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCoefNotoriete', array($coefNotoriete));

        return parent::setCoefNotoriete($coefNotoriete);
    }

    /**
     * {@inheritDoc}
     */
    public function getCoefNotoriete()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCoefNotoriete', array());

        return parent::getCoefNotoriete();
    }

    /**
     * {@inheritDoc}
     */
    public function setTypeMedecin(\CR\GSBRBundle\Entity\typePraticien $typeMedecin = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTypeMedecin', array($typeMedecin));

        return parent::setTypeMedecin($typeMedecin);
    }

    /**
     * {@inheritDoc}
     */
    public function getTypeMedecin()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTypeMedecin', array());

        return parent::getTypeMedecin();
    }

    /**
     * {@inheritDoc}
     */
    public function setAdresseMedecin($adresseMedecin)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setAdresseMedecin', array($adresseMedecin));

        return parent::setAdresseMedecin($adresseMedecin);
    }

    /**
     * {@inheritDoc}
     */
    public function getAdresseMedecin()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getAdresseMedecin', array());

        return parent::getAdresseMedecin();
    }

    /**
     * {@inheritDoc}
     */
    public function getPrenomNom()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPrenomNom', array());

        return parent::getPrenomNom();
    }

}
