<?php

namespace Proxies\__CG__\CR\GSBRBundle\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class medicament extends \CR\GSBRBundle\Entity\medicament implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array();



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return array('__isInitialized__', '' . "\0" . 'CR\\GSBRBundle\\Entity\\medicament' . "\0" . 'id', '' . "\0" . 'CR\\GSBRBundle\\Entity\\medicament' . "\0" . 'depotLegal', '' . "\0" . 'CR\\GSBRBundle\\Entity\\medicament' . "\0" . 'nomCommercial', '' . "\0" . 'CR\\GSBRBundle\\Entity\\medicament' . "\0" . 'composition', '' . "\0" . 'CR\\GSBRBundle\\Entity\\medicament' . "\0" . 'effets', '' . "\0" . 'CR\\GSBRBundle\\Entity\\medicament' . "\0" . 'contreIndication', '' . "\0" . 'CR\\GSBRBundle\\Entity\\medicament' . "\0" . 'prixEchantillon', '' . "\0" . 'CR\\GSBRBundle\\Entity\\medicament' . "\0" . 'famille');
        }

        return array('__isInitialized__', '' . "\0" . 'CR\\GSBRBundle\\Entity\\medicament' . "\0" . 'id', '' . "\0" . 'CR\\GSBRBundle\\Entity\\medicament' . "\0" . 'depotLegal', '' . "\0" . 'CR\\GSBRBundle\\Entity\\medicament' . "\0" . 'nomCommercial', '' . "\0" . 'CR\\GSBRBundle\\Entity\\medicament' . "\0" . 'composition', '' . "\0" . 'CR\\GSBRBundle\\Entity\\medicament' . "\0" . 'effets', '' . "\0" . 'CR\\GSBRBundle\\Entity\\medicament' . "\0" . 'contreIndication', '' . "\0" . 'CR\\GSBRBundle\\Entity\\medicament' . "\0" . 'prixEchantillon', '' . "\0" . 'CR\\GSBRBundle\\Entity\\medicament' . "\0" . 'famille');
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (medicament $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', array());
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', array());
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', array());

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function setDepotLegal($depotLegal)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDepotLegal', array($depotLegal));

        return parent::setDepotLegal($depotLegal);
    }

    /**
     * {@inheritDoc}
     */
    public function getDepotLegal()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDepotLegal', array());

        return parent::getDepotLegal();
    }

    /**
     * {@inheritDoc}
     */
    public function setNomCommercial($nomCommercial)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNomCommercial', array($nomCommercial));

        return parent::setNomCommercial($nomCommercial);
    }

    /**
     * {@inheritDoc}
     */
    public function getNomCommercial()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNomCommercial', array());

        return parent::getNomCommercial();
    }

    /**
     * {@inheritDoc}
     */
    public function setComposition($composition)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setComposition', array($composition));

        return parent::setComposition($composition);
    }

    /**
     * {@inheritDoc}
     */
    public function getComposition()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getComposition', array());

        return parent::getComposition();
    }

    /**
     * {@inheritDoc}
     */
    public function setEffets($effets)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setEffets', array($effets));

        return parent::setEffets($effets);
    }

    /**
     * {@inheritDoc}
     */
    public function getEffets()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getEffets', array());

        return parent::getEffets();
    }

    /**
     * {@inheritDoc}
     */
    public function setContreIndication($contreIndication)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setContreIndication', array($contreIndication));

        return parent::setContreIndication($contreIndication);
    }

    /**
     * {@inheritDoc}
     */
    public function getContreIndication()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getContreIndication', array());

        return parent::getContreIndication();
    }

    /**
     * {@inheritDoc}
     */
    public function setPrixEchantillon($prixEchantillon)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPrixEchantillon', array($prixEchantillon));

        return parent::setPrixEchantillon($prixEchantillon);
    }

    /**
     * {@inheritDoc}
     */
    public function getPrixEchantillon()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPrixEchantillon', array());

        return parent::getPrixEchantillon();
    }

    /**
     * {@inheritDoc}
     */
    public function setFamille(\CR\GSBRBundle\Entity\famille $famille = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setFamille', array($famille));

        return parent::setFamille($famille);
    }

    /**
     * {@inheritDoc}
     */
    public function getFamille()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getFamille', array());

        return parent::getFamille();
    }

}
